# Generated by Django 3.0.6 on 2020-06-20 23:16

from django.db import migrations , models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=15)) ,
                ('age' , models.IntegerField(default=18)) ,
                ('sex' , models.BooleanField(default=False)) ,
            ] ,
            options={
                'db_table': 'human' ,
            } ,
        ) ,
        migrations.CreateModel(
            name='Pet' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=15)) ,
                ('age' , models.IntegerField(default=18)) ,
                ('owner' , models.ForeignKey(on_delete=django.db.models.deletion.CASCADE , to='Admin.Human')) ,
            ] ,
            options={
                'db_table': 'pet' ,
            } ,
        ) ,
    ]
