# Generated by Django 3.0.6 on 2020-06-19 18:12

from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('address' , models.CharField(max_length=255)) ,
                ('owner' , models.IntegerField(blank=True , null=True)) ,
            ] ,
            options={
                'db_table': 'address' ,
            } ,
        ) ,
        migrations.CreateModel(
            name='User' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('username' , models.CharField(max_length=15)) ,
                ('password' , models.CharField(max_length=35)) ,
            ] ,
            options={
                'db_table': 'user' ,
            } ,
        ) ,
    ]
