# Generated by Django 3.0.6 on 2020-06-18 15:48

from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=15)) ,
                ('password' , models.CharField(max_length=225)) ,
                ('is_active' , models.BooleanField(default=False)) ,
                ('is_delete' , models.BooleanField(default=False)) ,
            ] ,
            options={
                'db_table': 'User' ,
            } ,
        ) ,
    ]
