# Generated by Django 3.0.6 on 2020-06-18 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Authentication' , '0001_initial') ,
    ]

    operations = [
        migrations.RenameField(
            model_name='user' ,
            old_name='is_active' ,
            new_name='is_super' ,
        ) ,
    ]
