# Generated by Django 3.0.6 on 2020-06-18 10:55

from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=155)) ,
                ('price' , models.IntegerField()) ,
            ] ,
            options={
                'db_table': 'book' ,
            } ,
        ) ,
    ]
