# Generated by Django 3.0.6 on 2020-06-18 11:59

from django.db import migrations , models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=10)) ,
                ('sex' , models.BooleanField(default=False)) ,
            ] ,
            options={
                'db_table': 'student' ,
            } ,
        ) ,
        migrations.CreateModel(
            name='Teacher' ,
            fields=[
                ('id' , models.AutoField(auto_created=True , primary_key=True , serialize=False , verbose_name='ID')) ,
                ('name' , models.CharField(max_length=10)) ,
                ('sex' , models.BooleanField(default=False)) ,
            ] ,
            options={
                'db_table': 'teacher' ,
            } ,
        ) ,
    ]
